
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
        hibernate:
            use-new-id-generator-mappings: true
            hbm2ddl:
              auto: update
              import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/projekt?autoReconnect=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  address: 127.0.0.1
  error:
    whitelabel:
      enabled: false
  tomcat:
    accesslog:
      enabled: true
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR

