package com.klima.projekt1.configuration;

public enum ErrorCode {
    USER_NOT_FOUND,
    ENTITY_NOT_FOUND,
    USER_UNAUTHORIZED,
    EVENT_NOT_FOUND,
    AUTH_SERVER_ERROR,
    MALFORMED_TOKEN,
    OFFICE_NOT_FOUND,
    COMMENT_NOT_FOUND,
    ROLE_NOT_FOUND,
    AVATAR_NOT_FOUND,
    NOTIFICATION_NOT_FOUND,
    OFFER_NOT_FOUND
}
